spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: a75882f783c2d87ec3f798d330ffb7f2
            client-secret: 0EAIYvVjbeqd7Zy70TWJNf5z3b9hmsNV
            redirect-uri: http://localhost:3000/login/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email, profile_nickname
            client-name: Kakao

          naver:
            client-id: HWQ9BzAAb1xWKWm0U6aV
            client-secret: CDhbwZpz57
            redirect-uri: http://localhost:3000/login/naver
            authorization-grant-type: authorization_code
            scope: email, name
            client-name: Naver

          google:
            client-id: 555482867273-rf3vnh1tqf9omcab07dfamq48elo5qho.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:3000/login/google
            scope: profile,email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response