spring:
  profiles:
    group:
      "local" : "local, jwt"
    active : local

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://farmer-db.cfnicvrzrvza.ap-northeast-2.rds.amazonaws.com/farmerDB?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: farmer123

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    web:
      pageable:
        default-page-size: 10

  jackson:
    serialization:
      fail-on-empty-beans: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.farmer.backend.controller.admin
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html            # Swagger UI ?? => localhost:8000//swagger-ui.html
    tags-sorter: alpha                # alpha: ??? ? ?? ??, method: HTTP Method ? ??
    operations-sorter: alpha          # alpha: ??? ? ?? ??, method: HTTP Method ? ??
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true

server:
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부
  forward-headers-strategy: framework

logging:
  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#    org.springframework: debug
#    org.springframework.web: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
