spring:
  profiles:
    group:
      "local" : "local, jwt, oauth, cloud"
    active : local

---
spring:
  profiles:
    include: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(/koEKCsdCMn32obOs3TbqG/akiFEdOF1lYuQLYabQdsNoUFxI1bv1eh4jpo4WnVLqxIBlCPFVKj6oUUag4POjnHAZcA3tCsOLI2YrXjSqoK4IbFRItKTkVs1AngQ7owI53UZ5k5tV15AmCtFbAL+Z97S5+hRPRgx9MmO3G+OMJQ0fLZUed3Njg==)
    username: ENC(tes9Ki6p8z1V6ycUPq3qdw==)
    password: ENC(b75JJtNMPkeZh6+d9aa1TAKJFcCNWLD0)

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    web:
      pageable:
        default-page-size: 10

  jackson:
    serialization:
      fail-on-empty-beans: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: my_jasypt_key

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.farmer.backend.api.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api/main/swagger-ui.html            # Swagger UI ?? => localhost:8000//swagger-ui.html
    tags-sorter: alpha                # alpha: ??? ? ?? ??, method: HTTP Method ? ??
    operations-sorter: alpha          # alpha: ??? ? ?? ??, method: HTTP Method ? ??
  api-docs:
    path: /api/main/api-docs
    groups:
      enabled: true
  cache:
    disabled: true

server:
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부
  forward-headers-strategy: framework

logging:
  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#    org.springframework: debug
#    org.springframework.web: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

    com :
      amazonaws:
        util:
          EC2MetadataUtils: error
